[package]
name = "rend-vk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { version = "0.37.0", features = ["linked", "debug"] }
ash-window = "0.10.0"
glam = "0.20.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
winit = "0.26.1"
